### ISSUE TITLE
Cancelling the adding of a tag

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#173]
Hi,

In some cases I need to cancel the adding of a tag by clicking on a "cancel" button. I tried something like this (I write a simplified version of my code).
In the template:
`<tag-input [ngModel]="tags" (onAdd)="addTag($event)></tag-input>`
`<button *ngIf="newTag" (click)="cancel()">Cancel</button>`

In the component:
`newTag: Tag;`
`addTag(tag: Tag) {`
`if (some condition) {...}`
`else {`
`this.newTag = tag`
`}`
`cancel() {`
`this.newTag = null`
`}`

But the tag don't disapear. Any possibility to do what I want ?

**Comment by Gbuomprisco** [comment]
Hi @sancaruso,

basically, you want to test a condition before adding a tag, right?

`onAdd` is an output, which means it gets fired *after* the tag is added.

You may want to use `transform`? This executes before the tag is added. If you return the string, then the tag is added, otherwise return a falsy value, and the item will get rejected. Let me know if this is not clear?

**Comment by sancaruso** [comment]
Thank you, I will try this!

**Comment by Gbuomprisco** [comment]
You can find an example in the demo. With the only difference the item is transformed to `@${item}`.

So - if you return `item`, it will be appended normally. If instead you return a falsy value, this won't get appended to the list of items :)

**Comment by sancaruso** [comment]
`transform` dit not make the job in my case (because I have to wait for a user event before cancelling). But I solved my problem using [(ngModel)] instead of [ngModel].

**Comment by Gbuomprisco** [comment]
glad it works anyway :)
