### ISSUE TITLE
ToLowerCase missing for autocomplete

### ISSUE THREAD

**Issue by jvielrco** [Gbuomprisco/ng2-tag-input#188]
Hello,

I think there is a toLowerCase missing in this method :

```
@Input() private matchingFn: (value: string, target: TagModel) => boolean =
         (value: string, target: TagModel): boolean => {
            const targetValue = target[this.displayBy].toString();

            return targetValue && targetValue
                .toLowerCase()
                .indexOf(value.toLowerCase()) >= 0 || false; <-- HERE
    };
```

(I'm using the last version 0.8.3)
Thanks

**Comment by z--aszlo** [comment]
Probably because if this the autocomplete doesn't work if I start to write with a capital letter... and very often that is the case. I was about to implement this for authors, was thinking that I can't get the plugin working but then hey, when I typed lowercase strings it found matches! :)

**Comment by jvielrco** [comment]
@z--aszlo : I didn't fix the problem in the library itself, instead I provided my own matchingFn function :
```
matchingFn(value: string, target: any): boolean {
        const targetValue = target.display.toString();

        return targetValue && targetValue
            .toLowerCase()
            .indexOf(value.toLowerCase()) >= 0 || false;
}
```

and in the view :
`    <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="allTags" [matchingFn]="matchingFn">`

**Comment by Gbuomprisco** [comment]
Hi @jvielrco,

Thanks for reporting&helping here. I'll find some time this week to fix this

**Comment by z--aszlo** [comment]
I think this issue is resolves as after doing again an npm install of this package, the matching does work. Only that know I get this error now at compile time coming from the updated ng-tag-input:

ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 5:22 in the original .ts file), resolving symbol Ng2DropdownModule in /home/laci/git/inventoryapp/node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts, resolving symbol TagInputModule in /home/laci/git/inventoryapp/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts, resolving symbol TagInputModule in /home/laci/git/inventoryapp/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts

**Comment by Gbuomprisco** [comment]
Hi @z--aszlo,

see https://github.com/Gbuomprisco/ng2-tag-input/issues/220
