### ISSUE TITLE
Unable to build an npm library (Error: /node_modules/ng2-tag-input/index.ts' is not under 'rootDir')

### ISSUE THREAD

**Issue by ayyazzafar** [Gbuomprisco/ng2-tag-input#458]
[x] bug report
[ ] feature request
[ ] support request/question

**Current behavior**
I am working on angular npm library. I installed ng2-tag-input in my library and tried to build my library but I got this error:
/node_modules/ng2-tag-input/index.ts' is not under 'rootDir'
MyLibrary/.tmp'. 'rootDir' is expected to contain all source files.

**Expected behavior**
It should let build my library without any error so that I can publish my library to npm. It works fine if I publish without ng2-tag-input

**Minimal reproduction of the problem with instructions (if applicable)**
1- Create a library using this generator: https://github.com/jvandemo/generator-angular2-library
2- Install ng2-tag-input
3- Run `npm run build`

Operating System: Windows 10
IDE: Visual Studio Code
I am using library generator to build my library (https://github.com/jvandemo/generator-angular2-library)

**Angular version:** 
4

**ng2-tag-input version:**
1.3.5

**Comment by Gbuomprisco** [comment]
Hi, the issue seems to be with the generator, not the library as it works OK with the cli instead.

**Comment by ayyazzafar** [comment]
Hi @Gbuomprisco Thanks for quick response.
I analyzed and realized that after installation, there should not be index.ts file in the plugin folder.
So I just removed index.ts file from this plugin's folder and it worked perfectly fine for library too. 

and yes it works perfectly fine with cli without need of deleting index.ts

Thanks again for your attention, time and amazing library. 
I am impressed as it is very useful and easy to use.

Regards
Ayyaz

**Comment by mebibou** [comment]
@Gbuomprisco I've seen many other issues in this repo with a similar problem. Currently I'm including `ng2-tags-input@1.0.5` in an Ionic app running `angular@4.4.6`, and it works. But I was trying to add it to a library that I compile and publish, but I've spent hours and hours on it and I always have some error related to metadata or rootDir. If I use `rootDir` in my `tsconfig.json`, I have the following error:
```
Error File '/library/node_modules/ng2-tag-input/index.ts' is not under 'rootDir'. 'rootDir' is expected to contain all source files.
```

When I point the rootDir to the root folder of the project, I get the error:
```
Error: ENOENT: no such file or directory, open './node_modules/ng2-tag-input/node_modules/ng2-material-dropdown/index.metadata.json'
```

By looking at the files in this library in my `node_modules` folder, there are no `.d.ts` files, no metadata files, which is odd because looking at other libraries that work well they are all build the same way, only this one is not. 
My `tsconfig.json` file:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "stripInternal": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "es2015",
    "moduleResolution": "node",
    "rootDir": ".",
    "target": "es5",
    "skipLibCheck": true,
    "lib": ["es2015", "dom"],
    "sourceMap": true,
    "inlineSources": true,
    "noImplicitAny": true
  },
  "files": []
}
```

**Comment by Gbuomprisco** [comment]
That library is very old: ngx-chips is the one you're looking for. It got renamed when angular bumped from v2

**Comment by mebibou** [comment]
@Gbuomprisco yes actually I just managed to unstuck myself after 3hours trying every combination possible. Using angular `4.4.6`, I managed to make it work using `ngx-chips@1.6.3`. Problem is that with recent version it only works with angular5+, and since you don't really bother keeping a CHANGELOG up to date, unless going through all the version is impossible to find a match. Can you at least say something about that in the README? or just state in the changelog the versions that work!

**Comment by Gbuomprisco** [comment]
Should I apologize for not taking care of details for a project I work on for free in my spare time? Choose another component if the work I do is not good enough for you.

**Comment by mebibou** [comment]
I'm just giving you a suggestion to help others having the same problem as me as I saw in many issues here and on SO. Up to you mate

**Comment by Gbuomprisco** [comment]
All you had to do was read a bunch of commits on the package.json to figure out how to match the current version with angular.

**Comment by mebibou** [comment]
No because only some of them work. So I had to try one by one until I found one that worked. But that's probably my stupidity for not being able to see the right one from the start
